// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSH5sEhfLJMbcwdZbz87l47WVw21D1O84',
    appId: '1:92720287535:web:3fc26d3821a1efe1cc5bda',
    messagingSenderId: '92720287535',
    projectId: 'mice-plan-bc6ae',
    authDomain: 'mice-plan-bc6ae.firebaseapp.com',
    storageBucket: 'mice-plan-bc6ae.firebasestorage.app',
    measurementId: 'G-BDVZ6WWD0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2pGremjNFmXOq8NXKXTBf5v9rbw23am4',
    appId: '1:92720287535:android:9a7e5e1a833d8341cc5bda',
    messagingSenderId: '92720287535',
    projectId: 'mice-plan-bc6ae',
    storageBucket: 'mice-plan-bc6ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBehZ0Q-sQWPwgokPdTVwl5x5Bj0J2g3U',
    appId: '1:92720287535:ios:231f96e9451a0260cc5bda',
    messagingSenderId: '92720287535',
    projectId: 'mice-plan-bc6ae',
    storageBucket: 'mice-plan-bc6ae.firebasestorage.app',
    iosBundleId: 'com.example.miceplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBehZ0Q-sQWPwgokPdTVwl5x5Bj0J2g3U',
    appId: '1:92720287535:ios:231f96e9451a0260cc5bda',
    messagingSenderId: '92720287535',
    projectId: 'mice-plan-bc6ae',
    storageBucket: 'mice-plan-bc6ae.firebasestorage.app',
    iosBundleId: 'com.example.miceplan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSH5sEhfLJMbcwdZbz87l47WVw21D1O84',
    appId: '1:92720287535:web:79f21d3e80d36a34cc5bda',
    messagingSenderId: '92720287535',
    projectId: 'mice-plan-bc6ae',
    authDomain: 'mice-plan-bc6ae.firebaseapp.com',
    storageBucket: 'mice-plan-bc6ae.firebasestorage.app',
    measurementId: 'G-HTF6KYETGP',
  );
}